server:
  port: 8080

# MongoDB connection
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

# JWT configuration
jwt:
  secret: ${JWT_SECRET}

# Logging config
logging:
  level:
    root: INFO
    com.resumeai.analyzer: DEBUG
    org.springframework: INFO