server:
  port: 8080

# MongoDB connection
spring:
  data:
    mongodb:
      uri: ${MongoDB_URI}
      auto-index-creation: true

# Logging config
logging:
  level:
    root: INFO
    com.resumeai.analyzer: DEBUG
    org.springframework: INFO

